name: Build Release x86

on:
  push:
    branches:
      - master

env:
  HOST_N_CORES: 2
  NINJA_STATUS: "[%f/%t %o/sec] "

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows MSVC Conan Release",
            os: windows-latest
          }

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: MSVC Build CMD
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: amd64_x86
    
    - name: Setup Arch
      shell: cmd
      run: echo set arch=x86> arch.cmd
    
    - name: Set multicore build
      shell: cmd
      run: |
        echo set CL=/MP>> arch.cmd
        echo set CONAN_CPU_COUNT=%HOST_N_CORES%>> arch.cmd
    
      
    - name: Download sources
      shell: cmd
      run: qt download
      
    - name: Build Openssl
      shell: cmd
      run: qt openssl
      
    - name: Configure Qt Core
      shell: cmd
      run: qt setup
      
    - name: Build Qt Core
      shell: cmd
      run: qt build
      
    - name: Build Component Qt Imageformats
      shell: cmd
      run: qt extra qtimageformats
      
    - name: build Component Qt Declarative
      shell: cmd
      run: qt extra qtdeclarative
      
    - name: build Component Qt Multimedia
      shell: cmd
      run: qt extra qtmultimedia
      
    - name: build Component Qt Webchannel
      shell: cmd
      run: qt extra qtwebchannel
      
    - name: Install Python 3
      uses: actions/setup-python@v1
      with:
        python-version: '3.9'

    - name: Install dependencies (Conan)
      run: pip3 install conan

    - name: Build qtwebkit (MSVC)
      shell: cmd
      run: qt qtwebkit
      
    - name: Packaging Qt
      shell: cmd
      run: qt pack
      
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: qt-release-x86
        path: qt5*.7z
